### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by zBearchenPlayz** [Muqsit/SkyWars-PocketMine#10]
I have the new skywars Plugin,and a normal User can't Open Chests!fixing!

**Comment by Adam1609** [comment]
Please check, I use the plugin and users can open the chest
- Have you tested the plugin with zero plugin enabled?

**Comment by zBearchenPlayz** [comment]
Zero Plugin?

**Comment by Muqsit** [comment]
Please elaborate the issue. One of your protection plugins is probably blocking you from opening chests.
