### ISSUE TITLE
if you aren't op you can't open the chests Why!?

### ISSUE THREAD

**Issue by XFIREGANER** [Muqsit/SkyWars-PocketMine#13]
Please tell me how to fix it

**Comment by Adam1609** [comment]
Have you tested without any plugin installation?

**Comment by Muqsit** [comment]
Either:
- PocketMine's spawn protection is interfering. Stop the server and set `spawn-protection` to `-1` in `server.properties`
- You have a land/world protection plugin that is interfering.
