### ISSUE TITLE
Joinsign

### ISSUE THREAD

**Issue by zBearchenPlayz** [Muqsit/SkyWars-PocketMine#6]
Hey!
If i have do all and Arena registred,i Join With sign,but i dont Join:-(
If i Tap Come nothing,and Error mit Coming!
Pls fixing the sign

**Comment by Muqsit** [comment]
Please send the error

**Comment by zBearchenPlayz** [comment]
Nono,i mean no Error,but i can't join!
If i Tap,nothing do.

**Comment by Muqsit** [comment]
You need to break and add the sign again, old signs (signs created using parent repo) don't work.

**Comment by zBearchenPlayz** [comment]
Ah okay thx,Now work
