### ISSUE TITLE
Fix Bug Please

### ISSUE THREAD

**Issue by lDavidMC** [Muqsit/SkyWars-PocketMine#7]
Please fix the bug that players can break and put blocks before the game starts. I do not know what version it is because I'm tracking the download and I'm testing the versions you're uploading to a poggit. The version I am using is PocketMine-MP 1.7dev-941 for Minecraft: PE [REDACTED] (protocol version 3.0.0-ALPHA12)

**Comment by zBearchenPlayz** [comment]
What the Problem?the Map reset:-)

**Comment by Adam1609** [comment]
Players can't break block while in cooldown, I think you are using the outdated version, please use up-to-date version please
