### ISSUE TITLE
Players sometime invisible in arena

### ISSUE THREAD

**Issue by Adam1609** [Muqsit/SkyWars-PocketMine#9]
## Issue description

It's normal in the first place, and then they disappeared, have tested with zero plugin

## Errors - CrashDumps

```
paste here or delete these lines
```

## Versions

- **SW_VERSION**: 0.7dev

- **POCKETMINE**: 1.7dev-918

**Comment by Muqsit** [comment]
Which commit of PocketMine are you on?

**Comment by Adam1609** [comment]
I'm using 1.7dev-918
https://github.com/pmmp/PocketMine-MP/releases/download/api%2F3.0.0-ALPHA12/PocketMine-MP.phar

**Comment by Adam1609** [comment]
I stand corrected, I will close this issue
